#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CALLER=$(ps ax | grep "^ *$PPID" | awk '{print $NF}')

symlinks=`find $DIR -type f -maxdepth 1 -name \.\*`

for file in $symlinks; do
  [ ! -h "${HOME}/$(basename $file)" ] && ln -s $file "${HOME}/$(basename $file)"
done

if [ -z "$(echo $CALLER | awk '/update/')" ]; then
  git branch --set-upstream master origin/master
  echo "Dotfiles have been installed."
else
  echo "Dotfiles have been updated."
fi

# antigen
brew install antigen

# janus/vim plugins
cd "${HOME}/.janus"

git clone git@github.com:editorconfig/editorconfig-vim.git 2>/dev/null || true
git clone https://github.com/mattn/emmet-vim.git 2>/dev/null || true
git clone git://github.com/godlygeek/tabular.git 2>/dev/null || true
git clone git://github.com/ntpeters/vim-better-whitespace.git 2>/dev/null || true
git clone https://github.com/flazz/vim-colorschemes.git 2>/dev/null || true
git clone git@github.com:dkprice/vim-easygrep.git 2>/dev/null || true
git clone git@github.com:Lokaltog/vim-easymotion.git 2>/dev/null || true
git clone git://github.com/tpope/vim-fugitive.git 2>/dev/null || true
git clone git@github.com:tpope/vim-speeddating.git 2>/dev/null || true
git clone git://github.com/shawncplus/phpcomplete.vim.git 2>/dev/null || true

# NPM dependencies
npm install -g yarn gulp prettyjson

# Homebrew dependencies
brew install gnu-sed ansible composer git ffmpeg autojump httpie htop go jq mariadb youtube-dl tmux telnet sqlite pandoc redis ruby gd imagemagick ssh-copy-id zsh bat exa nvm
